// ⚠️  GENERATED by scripts/stage-photos.mjs — do not edit by hand.
// Re-run `npm run stage:photos` after changing the photographs.
import type { StagePhotoId } from "./types";

/** A point on a photo, as percentages of its width and height. */
export interface StageAnchor { x: number; y?: number; n?: number }

export interface StagePhoto {
  id: StagePhotoId | "ac-dark";
  width: number;
  height: number;
  /** AVIF srcset, and a WebP src for anything without AVIF. */
  avif: string;
  fallback: string;
  /** A tiny blurred image that paints instantly while the real one decodes. */
  placeholder: string;
  /** Mean luminance, 0–255 — of the whole photo, and of the bands actually
   *  seen either side of the phone (what the scrim is solved against). */
  luma: number;
  seenLuma: number;
  /** Phone-focus scrim: the photo's shadow hue at a fixed darkness, and the
   *  alpha that lands this photo on the shared target luminance. */
  scrim: { color: string; alpha: number };
  /** The shadow hue lifted to a visible mid-tone — the phone's rim light. */
  glow: string;
  anchors: Record<string, StageAnchor | null>;
}

export const STAGE_PHOTOS: Record<StagePhotoId, StagePhoto> & { "ac-dark"?: StagePhoto } = {
  "ac": {
    "id": "ac",
    "width": 2880,
    "height": 2048,
    "avif": "/allhands/stage/ac-1920.avif 1920w, /allhands/stage/ac-2560.avif 2560w",
    "fallback": "/allhands/stage/ac-1920.webp",
    "placeholder": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBQCdASogABcAPtFcpEyoJaOiMBgIAQAaCWQAnTMy7HRx0Dzz69EapSVzVdNL8+rEdSj4AP70rbzFWzLXC14FWvfVujeVHO7imqHwvDs0bHFp47XffjzYJLG9BE38vDd0oanuEOwXdXDo+KcRO23OwQxY8VTVn9ob0Xhe8/h/b2Aj9k2yj/lv+htGKHtjhN6Z0oghl093IVAT9Hr6uLu8wNxDOnlFDwAAAA==",
    "luma": 57,
    "seenLuma": 65,
    "scrim": {
      "color": "#0e0404",
      "alpha": 0.73
    },
    "glow": "#e83a45",
    "anchors": {
      "thermostat": {
        "x": 84.3,
        "y": 51.9,
        "n": 80
      },
      "pendant": {
        "x": 41.7,
        "y": 35.5,
        "n": 75
      },
      "desk": {
        "x": 61.9,
        "y": 61,
        "n": 1875
      }
    }
  },
  "blinds-closed": {
    "id": "blinds-closed",
    "width": 2880,
    "height": 2048,
    "avif": "/allhands/stage/blinds-closed-1920.avif 1920w, /allhands/stage/blinds-closed-2560.avif 2560w",
    "fallback": "/allhands/stage/blinds-closed-1920.webp",
    "placeholder": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAQBQCdASogABcAPtFSpEuoJKOht/VYAQAaCWUAALvw3xRyDePYDAJ6DucPbuSFftZAAP76Yw5NV3/GGUHzybb0266SYhwRb3RFvpuitA8c8/WxYiXlv//94fPhx4OoIfJHf/369b1HP6koeQUx1OoAAAA=",
    "luma": 28,
    "seenLuma": 27,
    "scrim": {
      "color": "#0f0404",
      "alpha": 0.25
    },
    "glow": "#f0393e",
    "anchors": {
      "seam": {
        "x": 49.8
      }
    }
  },
  "blinds-open": {
    "id": "blinds-open",
    "width": 2880,
    "height": 2048,
    "avif": "/allhands/stage/blinds-open-1920.avif 1920w, /allhands/stage/blinds-open-2560.avif 2560w",
    "fallback": "/allhands/stage/blinds-open-1920.webp",
    "placeholder": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAADQBQCdASogABcAPtFapE0oJSMiMBgIAQAaCUATpl0QNvcB3ujZbO+1ygk4fl0bWPtJYcndg0EAAP7s/NtXPXF8ZYb3lLus81aKJG3WtXorACHmxi3ufj5kdGErbCdHUO1rumq8BC22mUICHK0+K6nRS67x5Pmo2jMlFfulkHF11mYcSPbaTtRLWj5UbvgYfeEBN/w2kIEsFAOvqjkGZ/J4yBCoCusrggZKnlswqzjOY69gSLAAAA==",
    "luma": 96,
    "seenLuma": 130,
    "scrim": {
      "color": "#0e0404",
      "alpha": 0.87
    },
    "glow": "#da3e47",
    "anchors": {}
  },
  "sunday": {
    "id": "sunday",
    "width": 2880,
    "height": 2048,
    "avif": "/allhands/stage/sunday-1920.avif 1920w, /allhands/stage/sunday-2560.avif 2560w",
    "fallback": "/allhands/stage/sunday-1920.webp",
    "placeholder": "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAACQBQCdASogABcAPtFcpk4oJSOiKAqpABoJZACsINiEt8JVoOBcsD2j4qViOghUvjgk/X9TAAD+97t+TL7luq7fz/o0+L2d7XBxpT9faUc7yqTg9DB7JVkVunmoXsOzmq15pdVq2R5mcKhsnVESTPldUmWLr1lDJ+5EiORQ3meiEBIktLnTeIgKlrd/hN7V4R8sSu8so+VYhlUlgaxQC325R9TLwvP9dCBv76OPByOxdNXzozWq2uyvwtw+lX5H8AA=",
    "luma": 92,
    "seenLuma": 128,
    "scrim": {
      "color": "#0e0405",
      "alpha": 0.87
    },
    "glow": "#d83e4d",
    "anchors": {}
  },
  "train": {
    "id": "train",
    "width": 2880,
    "height": 2048,
    "avif": "/allhands/stage/train-1920.avif 1920w, /allhands/stage/train-2560.avif 2560w",
    "fallback": "/allhands/stage/train-1920.webp",
    "placeholder": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBQCdASogABcAPtFQpEuoJKOhsBgMAQAaCUAUtYIdmgSHdWVytYHsCL69UzKweYvg5mygAP7q8eCMLRgfYpId1y2lb1mVAH6xUk87+HnkJOWOWTU/XUynibq8yQ0R4Ugi18qJMWWkR5cNaBNHPpsthmL6Gf1K6aFGiFjfUnjz96AeTZirQvypbbHawWwX+BLpCgAA",
    "luma": 113,
    "seenLuma": 109,
    "scrim": {
      "color": "#080604",
      "alpha": 0.84
    },
    "glow": "#7d5b40",
    "anchors": {}
  },
};
